name: sklad_inventar
description: Приложение для инвентаризации склада
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Сканер штрихкодов
  mobile_scanner: ^5.2.3

  # Локальное хранилище
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.3

  # HTTP для Telegram API и HTTP сервера
  http: ^1.2.1

  # mDNS автообнаружение сервера в сети
  multicast_dns: ^0.3.2+2

  # Управление состоянием
  provider: ^6.1.2

  # Уникальные ID
  uuid: ^4.4.0

  # UI
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  flutter_slidable: ^3.1.0
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
